name: Main workflow
on: [push]
env:
  container_name: regular-user-web-interface

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions/setup-node@v3
        with:
          node-version: "21.5.0"
      - name: "Install dependencies"
        run: |
          cd app
          npm install
      - name: "Building"
        run: |
          cd app
          npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions/setup-node@v3
        with:
          node-version: "21.5.0"
      - name: "Install dependencies"
        run: |
          cd app
          npm install
      - name: "Testing"
        run: |
          cd app
          npm run test

  push:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - run: |
          set -x

          docker build . -t $container_name

          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_USER_PASS }} ${{ vars.DOCKER_SERVER }}
          docker image tag $container_name ${{ vars.DOCKER_SERVER }}/$container_name
          docker push ${{ vars.DOCKER_SERVER }}/$container_name
